name: demo_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  faker: ^2.1.0
  dropdown_search: ^6.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  bcrypt: 1.1.3
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  mailer: ^6.1.0
  email_otp: ^3.0.2
  http: ^1.2.1
  provider: ^6.1.2
  geolocator: ^13.0.2
  bson: ^5.0.4
  geocoding: ^3.0.0
  location: ^7.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mongo_dart: ^0.10.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/Studio-Project-nobg.png
    # - assets/images/2x2_YNSON.png
    - assets/images/bmpapp_logo.png

fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/bmpapp_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/bmpapp_logo.png"

flutter_native_splash:
  image: "assets/images/bmpapp_logo.png"
  color: "42a5f5"
  android: true
